# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrappy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='origin',
            name='url',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
