# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrappy', '0002_origin_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='origin',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='origin',
            name='url',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
