# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 11:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrappy', '0003_auto_20160604_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='last_check',
        ),
    ]
