# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrappy', '0007_auto_20160605_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='last_score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.FloatField(),
        ),
    ]
