# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrappy', '0008_auto_20160605_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
